### ISSUE TITLE
Wikipedia example does not work

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/TopicBlob#1]
The Wikipedia example does not work, it errors when attempting to get the topics

**Comment by NinoDoko** [comment]
I think I have a solution for this - I'll create a PR in a minute, if you want, you can assign me to this.

**Comment by banjtheman** [comment]
Another possible solution to look at
https://stackoverflow.com/questions/56408849/after-applying-gensim-lda-topic-modeling-how-to-get-documents-with-highest-prob

Boils down to we aren't attributing topics and documents correctly, may have to use an LDA model if LSI cant attribute

**Comment by banjtheman** [comment]
This was helpful in ordering topics
https://stackoverflow.com/questions/58286505/how-can-i-get-the-topic-scores-attributed-to-a-document-on-gensim-lsi

**Comment by banjtheman** [comment]
got it working with updates closing
