### ISSUE TITLE
Dockerize TopicBlob

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/TopicBlob#2]
# What is the Task
Create a process that can build a docker image that contains all the data and the main_st.py

## Why do we want to do this
We want to be able to create a standalone container with all the components we want to run TopicBlob

## How can I get started?
1. Create Dockerfile
2. Add all requirements needed to run TopicBlob
3. Create a build script
4. Start the image
5. Run the example 

## Definition of Done
Docker image created that can run TopicBlob

**Comment by enflo** [comment]
can i help?

**Comment by banjtheman** [comment]
> 
> 
> can i help?

Sure get to it!

**Comment by chillerm** [comment]
Could you add me as a contributor?

**Comment by chillerm** [comment]
@banjtheman I've completed this if you could add me as a contributor to the repo I'll push and submit a PR.

**Comment by banjtheman** [comment]
> 
> 
> @banjtheman I've completed this if you could add me as a contributor to the repo I'll push and submit a PR.

You can fork the repo, and make a PR
https://www.digitalocean.com/community/tutorials/hacktoberfest-how-to-submit-your-first-pull-request-on-github

**Comment by chillerm** [comment]
Done.  Had a question about the token it says is missing.  Not sure about that.

https://github.com/banjtheman/TopicBlob/pull/27
