### ISSUE TITLE
Add abilty to pass in custom stop words

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/TopicBlob#3]
# What is the Task
Have the ability to pass in an optional custom stop word list

## Why do we want to do this
To block certain words from the model

## How can I get started?
1. I would make an extra arg to TopicBlob as a list of strings
https://github.com/banjtheman/TopicBlob/blob/main/topicblob/topic.py#L11

2. I would extend the base stop words with the passed in list
https://github.com/banjtheman/TopicBlob/blob/main/topicblob/gensim_topic_modeling.py#L22

## Definition of Done
Can add custom stop words to a TopicBlob

**Comment by csyhuang** [comment]
I'm interested to handle this issue. May I take it?

**Comment by banjtheman** [comment]
closed by #11
