### ISSUE TITLE
Setup Testing Framework

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/TopicBlob#4]
# What is the Task
We want to use pytest to test TopicBlob,  setup the framework for us to begin testing

## Why do we want to do this
To ensure TopicBlob works

## How can I get started?
1 Make a tests folder
2. place some stub tests https://github.com/pluralsight/intro-to-pytest/tree/master/tests
3. Have pytest run these tests

## Definition of Done
Can use pytest on repo

**Comment by yellalena** [comment]
hey can I work on it?

**Comment by yellalena** [comment]
does this mean "yes"? :D

**Comment by banjtheman** [comment]
yes
