### ISSUE TITLE
Create streamlit example

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/TopicBlob#6]
# What is the Task
Create an example using streamlit

## Why do we want to do this
So we can show of the tool in a web app

## How can I get started?
1. Create new streamlit app
2. Have a Textbox where users can enter in text
3. Allow them to enter more text as needed
4. Turn all the text into a TopicBlob
5. Show off the topic blob functions

- topic_search
- topics
- ranked_search
- show similar docs

## Definition of Done
Streamlit app created

**Comment by pedrogengo** [comment]
Hey, I would like to create this webapp!

**Comment by pedrogengo** [comment]
Can you assign me to this issue?

**Comment by banjtheman** [comment]
closed by #13
