### ISSUE TITLE
Update ranked search return

### ISSUE THREAD

**Issue by banjtheman** [banjtheman/TopicBlob#7]
# What is the Task
Return all attributes of topic blobs for ranked search

## Why do we want to do this
In order to give the user all information about the document

## How can I get started?
1. Update the code here
https://github.com/banjtheman/TopicBlob/blob/main/topicblob/gensim_topic_modeling.py#L63

2. Keep track of each doc in corpus docs

3. When docs are sorted get the full topicblob object and add it to the results

It might be confusing so ask any questions in the comments

## Definition of Done
Ranked search returns full object info

**Comment by iedr** [comment]
I would like to attempt this!

**Comment by banjtheman** [comment]
Fixed by #10
